"""
Security regression tests for PUT /api/v1/media/direct-upload (W1-1).

Tests verify:
- Unauthenticated requests are rejected (401)
- Keys outside the user's prefix are rejected (403)
- Path traversal attempts are rejected (400)
- Oversized uploads are rejected (413)
- Endpoint disabled in production environment (400)
- Disallowed extensions rejected (400)
- Sibling-prefix path traversal in storage_local (W1-5)
"""

from pathlib import Path
from unittest.mock import patch

import pytest
from httpx import AsyncClient

from backend.app.identity.dependencies import get_current_user
from backend.app.main import app

USER_ID = "upload_test_user_1"
OTHER_USER_ID = "upload_test_user_2"


def _make_user_override(user_id: str = USER_ID):
    async def override():
        return {
            "user_id": user_id,
            "name": "Upload Tester",
            "email": "uploader@test.com",
            "roles": ["user"],
        }
    return override


# Minimal valid 1x1 white PNG generated by spec
VALID_PNG = (
    b"\x89PNG\r\n\x1a\n"
    b"\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01"
    b"\x08\x02\x00\x00\x00\x90wS\xde"
    b"\x00\x00\x00\x0cIDATx\x9cc\xf8\x0f\x00\x00\x01\x01\x00\x05\x18\xd8N"
    b"\x00\x00\x00\x00IEND\xaeB`\x82"
)


@pytest.mark.asyncio
async def test_unauthenticated_upload_returns_401(async_client: AsyncClient, mock_db):
    """PUT /direct-upload without auth must return 401."""
    app.dependency_overrides.pop(get_current_user, None)
    res = await async_client.put(
        "/api/v1/media/direct-upload",
        params={"key": f"uploads/{USER_ID}/test.png"},
        content=VALID_PNG,
    )
    assert res.status_code == 401, f"Expected 401, got {res.status_code}: {res.text}"


@pytest.mark.asyncio
async def test_other_users_prefix_returns_403(async_client: AsyncClient, mock_db):
    """Uploading to another user's prefix must return 403."""
    app.dependency_overrides[get_current_user] = _make_user_override(USER_ID)
    try:
        res = await async_client.put(
            "/api/v1/media/direct-upload",
            params={"key": f"uploads/{OTHER_USER_ID}/evil.png"},
            content=VALID_PNG,
        )
        assert res.status_code == 403, f"Expected 403, got {res.status_code}: {res.text}"
    finally:
        app.dependency_overrides.pop(get_current_user, None)


@pytest.mark.asyncio
async def test_path_traversal_rejected(async_client: AsyncClient, mock_db):
    """Keys containing '..' or backslashes must be rejected."""
    app.dependency_overrides[get_current_user] = _make_user_override(USER_ID)
    try:
        traversal_keys = [
            f"uploads/{USER_ID}/../../etc/passwd",
            f"uploads/{USER_ID}/..\\..\\etc\\passwd",
            f"uploads/{USER_ID}/../{OTHER_USER_ID}/stolen.png",
            "/etc/passwd",
        ]
        for key in traversal_keys:
            res = await async_client.put(
                "/api/v1/media/direct-upload",
                params={"key": key},
                content=VALID_PNG,
            )
            assert res.status_code in (400, 403), (
                f"Traversal key '{key}' got {res.status_code}, expected 400/403"
            )
    finally:
        app.dependency_overrides.pop(get_current_user, None)


@pytest.mark.asyncio
async def test_oversize_upload_returns_413(async_client: AsyncClient, mock_db):
    """Uploads exceeding max size must be rejected with 413."""
    app.dependency_overrides[get_current_user] = _make_user_override(USER_ID)
    try:
        # Patch settings to use a tiny max so test runs fast
        with patch("backend.app.media.routes.settings") as mock_settings:
            mock_settings.environment = "development"
            mock_settings.max_image_size_bytes = 100  # 100 bytes cap
            mock_settings.max_video_size_bytes = 200

            oversized_body = b"x" * 200  # > 100 bytes
            res = await async_client.put(
                "/api/v1/media/direct-upload",
                params={"key": f"uploads/{USER_ID}/big.png"},
                content=oversized_body,
            )
            assert res.status_code == 413, f"Expected 413, got {res.status_code}: {res.text}"
    finally:
        app.dependency_overrides.pop(get_current_user, None)


@pytest.mark.asyncio
async def test_production_env_disables_endpoint(async_client: AsyncClient, mock_db):
    """Direct upload must be disabled in production."""
    app.dependency_overrides[get_current_user] = _make_user_override(USER_ID)
    try:
        with patch("backend.app.media.routes.settings") as mock_settings:
            mock_settings.environment = "production"
            res = await async_client.put(
                "/api/v1/media/direct-upload",
                params={"key": f"uploads/{USER_ID}/test.png"},
                content=VALID_PNG,
            )
            assert res.status_code == 400, f"Expected 400, got {res.status_code}: {res.text}"
            assert "production" in res.json()["detail"].lower()
    finally:
        app.dependency_overrides.pop(get_current_user, None)


@pytest.mark.asyncio
async def test_disallowed_extension_rejected(async_client: AsyncClient, mock_db):
    """Extensions not in the allow-list must be rejected."""
    app.dependency_overrides[get_current_user] = _make_user_override(USER_ID)
    try:
        res = await async_client.put(
            "/api/v1/media/direct-upload",
            params={"key": f"uploads/{USER_ID}/malware.exe"},
            content=b"MZ" + b"\x00" * 100,
        )
        assert res.status_code == 400, f"Expected 400, got {res.status_code}: {res.text}"
    finally:
        app.dependency_overrides.pop(get_current_user, None)


@pytest.mark.asyncio
async def test_sibling_prefix_directory_rejected(mock_db):
    """
    W1-5: _resolve_path must reject keys that resolve to a sibling directory
    whose name starts with the base_dir name (e.g. media_storage_evil).
    """
    import tempfile

    from backend.app.core.adapters.storage_local import LocalStorageAdapter

    with tempfile.TemporaryDirectory() as tmpdir:
        base = Path(tmpdir) / "media_storage"
        base.mkdir()
        evil = Path(tmpdir) / "media_storage_evil"
        evil.mkdir()
        (evil / "secret.txt").write_text("stolen data")

        adapter = LocalStorageAdapter(base_dir=base)

        # With the old str.startswith check, this would NOT raise because
        # str(media_storage_evil/...).startswith(str(media_storage)) is True
        # With is_relative_to, this correctly raises.
        with pytest.raises(ValueError, match="Path traversal"):
            adapter._resolve_path("../media_storage_evil/secret.txt")
